# =================================================================
# Spring API Gateway Configuration
# =================================================================

# Server Configuration
server:
  port: 8080

# Application Configuration
spring:
  application:
    name: api-gateway

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:admin}
      password: ${CONFIG_SERVER_PASSWORD:admin123}
      fail-fast: true  # Keep this true but add retry config
      retry:
        initial-interval: 1000    # Start with 1 second
        multiplier: 1.5          # Increase by 50% each attempt
        max-interval: 10000      # Max 10 seconds between attempts
        max-attempts: 10         # Try up to 10 times
      request-read-timeout: 5000 # 5 second timeout per request
      request-connect-timeout: 3000 # 3 second connection timeout
