# =================================================================
# Spring API Gateway Configuration
# =================================================================

# Server Configuration
server:
  port: 0

# Application Configuration
spring:
  application:
    name: api-gateway

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
