# =================================================================
# Spring Cloud Config Server Configuration
# =================================================================

# Server Configuration
server:
  port: 8761

# Application Configuration
spring:
  application:
    name: discovery-service

# Eureka Server Configuration
eureka:
  server:
    enable-self-preservation: false   # Disable self-preservation mode for testing purposes
  client:
    register-with-eureka: false
    fetch-registry: false

# =================================================================
# Monitoring & Management Configuration
# =================================================================

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,configprops
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true
